version: '3'
services:
  juice-shop:
    image: bkimminich/juice-shop:v14.5.1
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
